baseURL = "https://vanvj00001.github.io/my-blog/"
title = "空中小屋"
theme = "hugo-book"
languageCode = "zh-cn"

disablePathToLower = true
enableGitInfo = true

[markup]
  [markup.goldmark.renderer]
    unsafe = true

  [markup.tableOfContents]
    startLevel = 1

  [markup.highlight]
    style = 'base16-snazzy'

[taxonomies]
  tag = 'tags'
  category = 'categories'

[menu]
  [[menu.main]]
    name = '博客'
    url = '/posts/'
    weight = 1

  [[menu.main]]
    name = '标签'
    url = '/tags/'
    weight = 2

  [[menu.main]]
    name = '分类'
    url = '/categories/'
    weight = 3

  [[menu.main]]
    name = '关于'
    url = '/about/'
    weight = 4

[languages]
  [languages.en]
    languageName = 'English'
    weight = 1

[params]
  author = '老梵'
  description = 'A blog for sharing thoughts and ideas'
  BookTheme = 'auto'
  BookSection = 'posts'
  BookDateFormat = 'January 2, 2006'
  BookSearch = true
  BookComments = false
  BookPortableLinks = false

