

baseURL = 'https://vanvj00001.github.io/my-blog/'
languageCode = 'zh-cn'
title = '老梵的随笔空间'
theme = 'PaperMod'

[params]
description = '老梵的个人随笔和思考'
author = '老梵'
showVisitedLinks = true
showReadingTime = true
summaryLength = 200


[author]
name = '老梵'

